FROM nginx:1.11
ENV TZ=Asia/Shanghai
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./enable-php.conf /etc/nginx/enable-php.conf
#COPY ./lssea /home/wwwroot/www.lssea.com
COPY ./fastcgi.conf /etc/nginx/fastcgi.conf
COPY ./lssea.nginx.conf /etc/nginx/vhost/lssea.nginx.conf
#CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
