version: '2'
services:
    nginx:
        image: "lnmp-nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        volumes:
            - ./lssea:/home/wwwroot/www.lssea.com
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: "lnmp-php:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.php
        networks:
            - frontend
            - backend
        volumes:
            - ./lssea:/home/wwwroot/www.lssea.com
        environment:
            MYSQL_PASSWORD: cancel
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: cancel
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
